---
title: "Chapter 3"
output: word_document
---

```{r}
library(datasets)
library(tidyverse) 
library(MASS)
library(scatterplot3d)
library(ggplot2)
library(GGally)
```

## Histogram

```{r}
hist(airquality$Temp, xlab = "Temperature", main = "Temperatures in NYC May 1 - Sep 30 1973") #plot histogram with labels
```

```{r}
#plot histogram with probability, column represents area
hist(airquality$Temp, xlab = "Temperature", main = "Temperatures in NYC May 1 - Sep 30 1973", probability = TRUE)
lines(density(airquality$Temp))  #add line for trend
```

## Bar plot

```{r}
table(Cars93$Type)
barplot(table(Cars93$Type), ylim = c(0,25), xlab = "Type", ylab = "Frequency", axis.lty = "solid", space = 0.5)
#ylim limit size of y axis
#axis.lty put solid line
#space put space between bars
```

```{r}
ex1 = filter(Cars93, Origin == "USA")
barplot(table(ex1$Type))
ex2 = filter(Cars93, Origin != "USA")
barplot(table(ex2$Type))
```

```{r}
females = HairEyeColor[,,2]
females
colornames = c("brown","blue", "salmon2", "green")
t(females)
barplot(t(females), beside = T, ylim=c(0,70), xlab="Hair Color", ylab="Frequency of eye color", col = colornames, axis.lty = "solid")
legend("top", rownames(t(females)), cex = 0.8, fill = colornames, title = "Eye Color")
```

```{r}
colors()
```

```{r}
males = HairEyeColor[,,1]
males
colornames = c("brown","blue", "salmon2", "green")
t(males)
barplot(t(males), beside = T, ylim=c(0,70), xlab="Hair Color", ylab="Frequency of eye color", col = colornames, axis.lty = "solid")
legend("top", rownames(t(males)), cex = 0.8, fill = colornames, title = "Eye Color")
```

## Pie Chart

```{r}
pie(table(Cars93$Type))
```

## Scatterplot

```{r}
plot(airquality$Wind~airquality$Temp, pch=16, xlab="Wind Velocity (MPH)", ylab="Temperature (Fahrenheit)", main="Temperature vs Wind Velocity")
```

## Matrix Plot

```{r}
oz.tp.wd <- subset(airquality, select = c(Ozone, Temp, Wind))
pairs(oz.tp.wd)
```

## Box plot

```{r}
boxplot(Temp ~ Month, data=airquality, xaxt = "n")
axis(1, at=1:5, label=c("May", "June", "July", "August", "September"))
```

## ggplot

```{r}
ggplot(airquality, aes(x=Temp)) + geom_histogram(binwidth = 5,color= "black", fill = "grey80") + theme_bw() + 
      labs(x="Temperature", y="Frequency", title = "Temperature in airquality data frame")   #histogram
```

```{r}
ggplot(Cars93,aes(x=Type))+geom_bar()+labs(y="Frequency", title = "Car Type and Frequency in Cars93")  #bar graph
ggplot(Cars93,aes(x=Type,fill=Origin))+geom_bar(position = "dodge", color = "black")+scale_fill_grey(start=0,end=1) #grouped bar graph
```

```{r}
female.df = data.frame(females)
ggplot(female.df,aes(x=Hair,y=Freq,fill=Eye))+geom_bar(position = "dodge", color = "black",stat="identity")+scale_fill_grey(start=0,end=1) #grouped bargraph
```

```{r}
ggplot(airquality,aes(x=Wind,y=Temp)) + geom_point()  #scattertplot
```

```{r}
airnona = drop_na(airquality)
median.ozone = median(airnona$Ozone)
ozonelvl = NULL
for(i in 1:nrow(airnona)){
  if(airnona$Ozone[i] <= median.ozone){
    ozonelvl[i] = "Low"}
  else{ozonelvl[i] = "High"}
}
nOzonelevel = cbind(airnona,ozonelvl)
ggplot(nOzonelevel,aes(x=Wind,y=Temp, color=ozonelvl)) + geom_point(size=3) + scale_color_grey(start=0, end=1) #plot scatter plot based on class
```

```{r}
with(nOzonelevel,scatterplot3d(Wind~Temp+Ozone, pch = 19)) #3d scatter plot
```

```{r}
airset = subset(airnona, select = c(Ozone, Wind, Temp, Solar.R)) #ggplot with correlation matrix
ggpairs(airset)
```

```{r}
ggplot(airquality, aes(x=as.factor(Month),y=Temp)) + geom_boxplot() + geom_point() + labs(y="Temperature", x="Month") +
      scale_x_discrete(labels=c("May", "June", "July", "August", "September"))   #ggplot with boxplot
```
